# Generated by Django 2.0.2 on 2018-11-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='注册码')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='注册码生成时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('sex', models.CharField(default='1', max_length=12, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirmed', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
        ),
        migrations.AddField(
            model_name='confirm',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ajax_app.User', verbose_name='关联的用户'),
        ),
    ]
