# Generated by Django 2.0.2 on 2018-11-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confirm',
            new_name='ConfirmString',
        ),
        migrations.AlterModelTable(
            name='confirmstring',
            table='ConfirmString',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
